![](TN-comunidades-Instituto-Tecnologico-de-Durango.png)
 
<div style = "Text-align: center">
    
# Analisis de datos masivos
## Introduccion a las Dataframes en PANDAS
## Nombre del docente 
### Jose Gabriel Rodriguez Rivas
## Nombre del alumno
### Oswaldo Zura Alvarado
    
</div>

## Tabla de contenido
[1-. Introduccion a dataframes](#id1)<br>
[2-. Indexing DataFrame](#id2)<br>
[3-. Transpuesta de un DataFrame](#id3)<br>
[4-. Copiar DataFrames](#id4)<br>
[5-. Load CSV as DataFrames](#id5)<br>
[6-. Busquedas en un DataFrame](#id6)<br>
[7-. Group by](#id7)<br>

## Introduccion a dataframes <a id=id1> <a/>

In [1]:
import pandas as pd

In [2]:
Alumno1 = pd.Series({'Nombre':'Juan', 'Fecha Nacimiento':'10-02-2000', 'Carrera':'IINF', 'Edad':20})
Alumno2 = pd.Series({'Nombre':'Karla', 'Fecha Nacimiento':'18-05-2001', 'Carrera':'ISIC', 'Edad':19})
Alumno3 = pd.Series({'Nombre':'Pedro', 'Fecha Nacimiento':'15-07-1998', 'Carrera':'IINF', 'Edad':22})
Alumno4 = pd.Series({'Nombre':'Maria', 'Fecha Nacimiento':'10-12-1999', 'Carrera':'ITIC', 'Edad':19})

In [3]:
Alumnos = pd.DataFrame([Alumno1, Alumno2, Alumno3, Alumno4])
Alumnos

  Nombre Fecha Nacimiento Carrera  Edad
0   Juan       10-02-2000    IINF    20
1  Karla       18-05-2001    ISIC    19
2  Pedro       15-07-1998    IINF    22
3  Maria       10-12-1999    ITIC    19

In [4]:
Alumnos.iloc[1]

Nombre                   Karla
Fecha Nacimiento    18-05-2001
Carrera                   ISIC
Edad                        19
Name: 1, dtype: object

## Indexing DataFrame <a id=id2> <a/>

In [5]:
Alumnos = Alumnos.set_index('Carrera')
Alumnos

        Nombre Fecha Nacimiento  Edad
Carrera
IINF      Juan       10-02-2000    20
ISIC     Karla       18-05-2001    19
IINF     Pedro       15-07-1998    22
ITIC     Maria       10-12-1999    19

In [6]:
Alumnos.loc['IINF']

        Nombre Fecha Nacimiento  Edad
Carrera
IINF      Juan       10-02-2000    20
IINF     Pedro       15-07-1998    22

In [7]:
Alumnos.loc['ISIC']

Nombre                   Karla
Fecha Nacimiento    18-05-2001
Edad                        19
Name: ISIC, dtype: object

In [8]:
Alumnos.loc['IINF', 'Nombre']

Carrera
IINF     Juan
IINF    Pedro
Name: Nombre, dtype: object

In [9]:
Alumnos.loc['IINF', ['Nombre','Edad']]

        Nombre  Edad
Carrera
IINF      Juan    20
IINF     Pedro    22

## Transpuesta de un DataFrame <a id=id3> <a/>

In [10]:
Alumnos.T

Carrera                 IINF        ISIC        IINF        ITIC
Nombre                  Juan       Karla       Pedro       Maria
Fecha Nacimiento  10-02-2000  18-05-2001  15-07-1998  10-12-1999
Edad                      20          19          22          19

In [11]:
Alumnos['Carrera'] = Alumnos.index
Alumnos = Alumnos.set_index('Nombre')
Alumnos

       Fecha Nacimiento  Edad Carrera
Nombre
Juan         10-02-2000    20    IINF
Karla        18-05-2001    19    ISIC
Pedro        15-07-1998    22    IINF
Maria        10-12-1999    19    ITIC

In [12]:
Alumnos = Alumnos.reset_index()
Alumnos

  Nombre Fecha Nacimiento  Edad Carrera
0   Juan       10-02-2000    20    IINF
1  Karla       18-05-2001    19    ISIC
2  Pedro       15-07-1998    22    IINF
3  Maria       10-12-1999    19    ITIC

## Copiar DataFrames <a id=id4> <a/>

In [19]:
copia_Alumnos = Alumnos.copy()
copia_Alumnos

  Nombre Fecha Nacimiento  Edad Carrera
0   Juan       10-02-2000    20    IINF
1  Karla       18-05-2001    19    ISIC
2  Pedro       15-07-1998    22    IINF
3  Maria       10-12-1999    19    ITIC

## Load CSV as DataFrames <a id=id5> <a/>

In [14]:
df = pd.read_csv('olympics.csv')
df

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15
0,NaN,№ Summer,01 !,02 !,03 !,Total,№ Winter,01 !,02 !,03 !,Total,№ Games,01 !,02 !,03 !,Combined total
1,Afghanistan (AFG),13,0,0,2,2,0,0,0,0,0,13,0,0,2,2
2,Algeria (ALG),12,5,2,8,15,3,0,0,0,0,15,5,2,8,15
3,Argentina (ARG),23,18,24,28,70,18,0,0,0,0,41,18,24,28,70
4,Armenia (ARM),5,1,2,9,12,6,0,0,0,0,11,1,2,9,12
5,Australasia (ANZ) [ANZ],2,3,4,5,12,0,0,0,0,0,2,3,4,5,12
6,Australia (AUS) [AUS] [Z],25,139,152,177,468,18,5,3,4,12,43,144,155,181,480
7,Austria (AUT),26,18,33,35,86,22,59,78,81,218,48,77,111,116,304
8,Azerbaijan (AZE),5,6,5,15,26,5,0,0,0,0,10,6,5,15,26
9,Bahamas (BAH),15,5,2,5,12,0,0,0,0,0,15,5,2,5,12
10,Bahrain (BRN),8,0,0,1,1,0,0,0,0,0,8,0,0,1,1
11,Barbados (BAR) [BAR],11,0,0,1,1,0,0,0,0,0,11,0,0,1,1
12,Belarus (BLR),5,12,24,39,75,6,6,4,5,15,11,18,28,44,90
13,Belgium (BEL),25,37,52,53,142,20,1,1,3,5,45,38,53,56,147
14,Bermuda (BER),17,0,0,1,1,7,0,0,0,0,24,0,0,1,1
15,Bohemia (BOH) [BOH] [Z],3,0,1,3,4,0,0,0,0,0,3,0,1,3,4
16,Botswana (BOT),9,0,1,0,1,0,0,0,0,0,9,0,1,0,1
17,Brazil (BRA),21,23,30,55,108,7,0,0,0,0,28,23,30,55,108
18,British West Indies (BWI) [BWI],1,0,0,2,2,0,0,0,0,0,1,0,0,2,2
19,Bulgaria (BUL) [H],19,51,85,78,214,19,1,2,3,6,38,52,87,81,220
20,Burundi (BDI),5,1,0,0,1,0,0,0,0,0,5,1,0,0,1
21,Cameroon (CMR),13,3,1,1,5,1,0,0,0,0,14,3,1,1,5
22,Canada (CAN),25,59,99,121,279,22,62,56,52,170,47,121,155,173,449
23,Chile (CHI) [I],22,2,7,4,13,16,0,0,0,0,38,2,7,4,13
24,China (CHN) [CHN],9,201,146,126,473,10,12,22,19,53,19,213,168,145,526
25,Colombia (COL),18,2,6,11,19,1,0,0,0,0,19,2,6,11,19
26,Costa Rica (CRC),14,1,1,2,4,6,0,0,0,0,20,1,1,2,4
27,Ivory Coast (CIV) [CIV],12,0,1,0,1,0,0,0,0,0,12,0,1,0,1
28,Croatia (CRO),6,6,7,10,23,7,4,6,1,11,13,10,13,11,34
29,Cuba (CUB) [Z],19,72,67,70,209,0,0,0,0,0,19,72,67,70,209
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
118,Sri Lanka (SRI) [SRI],16,0,2,0,2,0,0,0,0,0,16,0,2,0,2
119,Sudan (SUD),11,0,1,0,1,0,0,0,0,0,11,0,1,0,1
120,Suriname (SUR) [E],11,1,0,1,2,0,0,0,0,0,11,1,0,1,2
121,Sweden (SWE) [Z],26,143,164,176,483,22,50,40,54,144,48,193,204,230,627
122,Switzerland (SUI),27,47,73,65,185,22,50,40,48,138,49,97,113,113,323
123,Syria (SYR),12,1,1,1,3,0,0,0,0,0,12,1,1,1,3
124,Chinese Taipei (TPE) [TPE] [TPE2],13,2,7,12,21,11,0,0,0,0,24,2,7,12,21
125,Tajikistan (TJK),5,0,1,2,3,4,0,0,0,0,9,0,1,2,3
126,Tanzania (TAN) [TAN],12,0,2,0,2,0,0,0,0,0,12,0,2,0,2
127,Thailand (THA),15,7,6,11,24,3,0,0,0,0,18,7,6,11,24
128,Togo (TOG),9,0,0,1,1,1,0,0,0,0,10,0,0,1,1
129,Tonga (TGA),8,0,1,0,1,1,0,0,0,0,9,0,1,0,1
130,Trinidad and Tobago (TRI) [TRI],16,2,5,11,18,3,0,0,0,0,19,2,5,11,18
131,Tunisia (TUN),13,3,3,4,10,0,0,0,0,0,13,3,3,4,10
132,Turkey (TUR),21,39,25,24,88,16,0,0,0,0,37,39,25,24,88
133,Uganda (UGA),14,2,3,2,7,0,0,0,0,0,14,2,3,2,7
134,Ukraine (UKR),5,33,27,55,115,6,2,1,4,7,11,35,28,59,122
135,United Arab Emirates (UAE),8,1,0,0,1,0,0,0,0,0,8,1,0,0,1
136,United States (USA) [P] [Q] [R] [Z],26,976,757,666,2399,22,96,102,84,282,48,1072,859,750,2681
137,Uruguay (URU),20,2,2,6,10,1,0,0,0,0,21,2,2,6,10
138,Uzbekistan (UZB),5,5,5,10,20,6,1,0,0,1,11,6,5,10,21
139,Venezuela (VEN),17,2,2,8,12,4,0,0,0,0,21,2,2,8,12
140,Vietnam (VIE),14,0,2,0,2,0,0,0,0,0,14,0,2,0,2
141,Virgin Islands (ISV),11,0,1,0,1,7,0,0,0,0,18,0,1,0,1
142,Yugoslavia (YUG) [YUG],16,26,29,28,83,14,0,3,1,4,30,26,32,29,87
143,Independent Olympic Participants (IOP) [IOP],1,0,1,2,3,0,0,0,0,0,1,0,1,2,3
144,Zambia (ZAM) [ZAM],12,0,1,1,2,0,0,0,0,0,12,0,1,1,2
145,Zimbabwe (ZIM) [ZIM],12,3,4,1,8,1,0,0,0,0,13,3,4,1,8
146,Mixed team (ZZX) [ZZX],3,8,5,4,17,0,0,0,0,0,3,8,5,4,17
147,Totals,27,4809,4775,5130,14714,22,959,958,948,2865,49,5768,5733,6078,17579

In [15]:
df.head()

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15
0,NaN,№ Summer,01 !,02 !,03 !,Total,№ Winter,01 !,02 !,03 !,Total,№ Games,01 !,02 !,03 !,Combined total
1,Afghanistan (AFG),13,0,0,2,2,0,0,0,0,0,13,0,0,2,2
2,Algeria (ALG),12,5,2,8,15,3,0,0,0,0,15,5,2,8,15
3,Argentina (ARG),23,18,24,28,70,18,0,0,0,0,41,18,24,28,70
4,Armenia (ARM),5,1,2,9,12,6,0,0,0,0,11,1,2,9,12

In [16]:
df = pd.read_csv('olympics.csv', index_col = 0, skiprows = 1)
df.head()

,№ Summer,01 !,02 !,03 !,Total,№ Winter,01 !.1,02 !.1,03 !.1,Total.1,№ Games,01 !.2,02 !.2,03 !.2,Combined total
Afghanistan (AFG),13,0,0,2,2,0,0,0,0,0,13,0,0,2,2
Algeria (ALG),12,5,2,8,15,3,0,0,0,0,15,5,2,8,15
Argentina (ARG),23,18,24,28,70,18,0,0,0,0,41,18,24,28,70
Armenia (ARM),5,1,2,9,12,6,0,0,0,0,11,1,2,9,12
Australasia (ANZ) [ANZ],2,3,4,5,12,0,0,0,0,0,2,3,4,5,12

In [17]:
df.columns

Index(['№ Summer', '01 !', '02 !', '03 !', 'Total', '№ Winter', '01 !.1',
       '02 !.1', '03 !.1', 'Total.1', '№ Games', '01 !.2', '02 !.2', '03 !.2',
       'Combined total'],
      dtype='object')

In [18]:
for col in df.columns:
    if col[:2] == '01':
        df.rename(columns = {col:'Gold' + col[4:]}, inplace = True)
    if col[:2] == '02':
        df.rename(columns = {col:'Silver' + col[4:]}, inplace = True)
    if col[:2] == '03':
        df.rename(columns = {col:'Bronze' + col[4:]}, inplace = True)
df.head()

,№ Summer,Gold,Silver,Bronze,Total,№ Winter,Gold.1,Silver.1,Bronze.1,Total.1,№ Games,Gold.2,Silver.2,Bronze.2,Combined total
Afghanistan (AFG),13,0,0,2,2,0,0,0,0,0,13,0,0,2,2
Algeria (ALG),12,5,2,8,15,3,0,0,0,0,15,5,2,8,15
Argentina (ARG),23,18,24,28,70,18,0,0,0,0,41,18,24,28,70
Armenia (ARM),5,1,2,9,12,6,0,0,0,0,11,1,2,9,12
Australasia (ANZ) [ANZ],2,3,4,5,12,0,0,0,0,0,2,3,4,5,12

## Busquedas en un DataFrame <a id=id6> <a/>

In [20]:
df['Gold'] > 0
df['Gold'].head(10) > 0

Afghanistan (AFG)            False
Algeria (ALG)                 True
Argentina (ARG)               True
Armenia (ARM)                 True
Australasia (ANZ) [ANZ]       True
Australia (AUS) [AUS] [Z]     True
Austria (AUT)                 True
Azerbaijan (AZE)              True
Bahamas (BAH)                 True
Bahrain (BRN)                False
Name: Gold, dtype: bool

In [21]:
ganadores_oro = df.where(df['Gold'] > 0)
ganadores_oro

,№ Summer,Gold,Silver,Bronze,Total,№ Winter,Gold.1,Silver.1,Bronze.1,Total.1,№ Games,Gold.2,Silver.2,Bronze.2,Combined total
Afghanistan (AFG),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Algeria (ALG),12.0,5.0,2.0,8.0,15.0,3.0,0.0,0.0,0.0,0.0,15.0,5.0,2.0,8.0,15.0
Argentina (ARG),23.0,18.0,24.0,28.0,70.0,18.0,0.0,0.0,0.0,0.0,41.0,18.0,24.0,28.0,70.0
Armenia (ARM),5.0,1.0,2.0,9.0,12.0,6.0,0.0,0.0,0.0,0.0,11.0,1.0,2.0,9.0,12.0
Australasia (ANZ) [ANZ],2.0,3.0,4.0,5.0,12.0,0.0,0.0,0.0,0.0,0.0,2.0,3.0,4.0,5.0,12.0
Australia (AUS) [AUS] [Z],25.0,139.0,152.0,177.0,468.0,18.0,5.0,3.0,4.0,12.0,43.0,144.0,155.0,181.0,480.0
Austria (AUT),26.0,18.0,33.0,35.0,86.0,22.0,59.0,78.0,81.0,218.0,48.0,77.0,111.0,116.0,304.0
Azerbaijan (AZE),5.0,6.0,5.0,15.0,26.0,5.0,0.0,0.0,0.0,0.0,10.0,6.0,5.0,15.0,26.0
Bahamas (BAH),15.0,5.0,2.0,5.0,12.0,0.0,0.0,0.0,0.0,0.0,15.0,5.0,2.0,5.0,12.0
Bahrain (BRN),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Barbados (BAR) [BAR],NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Belarus (BLR),5.0,12.0,24.0,39.0,75.0,6.0,6.0,4.0,5.0,15.0,11.0,18.0,28.0,44.0,90.0
Belgium (BEL),25.0,37.0,52.0,53.0,142.0,20.0,1.0,1.0,3.0,5.0,45.0,38.0,53.0,56.0,147.0
Bermuda (BER),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Bohemia (BOH) [BOH] [Z],NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Botswana (BOT),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Brazil (BRA),21.0,23.0,30.0,55.0,108.0,7.0,0.0,0.0,0.0,0.0,28.0,23.0,30.0,55.0,108.0
British West Indies (BWI) [BWI],NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Bulgaria (BUL) [H],19.0,51.0,85.0,78.0,214.0,19.0,1.0,2.0,3.0,6.0,38.0,52.0,87.0,81.0,220.0
Burundi (BDI),5.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,5.0,1.0,0.0,0.0,1.0
Cameroon (CMR),13.0,3.0,1.0,1.0,5.0,1.0,0.0,0.0,0.0,0.0,14.0,3.0,1.0,1.0,5.0
Canada (CAN),25.0,59.0,99.0,121.0,279.0,22.0,62.0,56.0,52.0,170.0,47.0,121.0,155.0,173.0,449.0
Chile (CHI) [I],22.0,2.0,7.0,4.0,13.0,16.0,0.0,0.0,0.0,0.0,38.0,2.0,7.0,4.0,13.0
China (CHN) [CHN],9.0,201.0,146.0,126.0,473.0,10.0,12.0,22.0,19.0,53.0,19.0,213.0,168.0,145.0,526.0
Colombia (COL),18.0,2.0,6.0,11.0,19.0,1.0,0.0,0.0,0.0,0.0,19.0,2.0,6.0,11.0,19.0
Costa Rica (CRC),14.0,1.0,1.0,2.0,4.0,6.0,0.0,0.0,0.0,0.0,20.0,1.0,1.0,2.0,4.0
Ivory Coast (CIV) [CIV],NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Croatia (CRO),6.0,6.0,7.0,10.0,23.0,7.0,4.0,6.0,1.0,11.0,13.0,10.0,13.0,11.0,34.0
Cuba (CUB) [Z],19.0,72.0,67.0,70.0,209.0,0.0,0.0,0.0,0.0,0.0,19.0,72.0,67.0,70.0,209.0
Cyprus (CYP),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Sri Lanka (SRI) [SRI],NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Sudan (SUD),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Suriname (SUR) [E],11.0,1.0,0.0,1.0,2.0,0.0,0.0,0.0,0.0,0.0,11.0,1.0,0.0,1.0,2.0
Sweden (SWE) [Z],26.0,143.0,164.0,176.0,483.0,22.0,50.0,40.0,54.0,144.0,48.0,193.0,204.0,230.0,627.0
Switzerland (SUI),27.0,47.0,73.0,65.0,185.0,22.0,50.0,40.0,48.0,138.0,49.0,97.0,113.0,113.0,323.0
Syria (SYR),12.0,1.0,1.0,1.0,3.0,0.0,0.0,0.0,0.0,0.0,12.0,1.0,1.0,1.0,3.0
Chinese Taipei (TPE) [TPE] [TPE2],13.0,2.0,7.0,12.0,21.0,11.0,0.0,0.0,0.0,0.0,24.0,2.0,7.0,12.0,21.0
Tajikistan (TJK),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Tanzania (TAN) [TAN],NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Thailand (THA),15.0,7.0,6.0,11.0,24.0,3.0,0.0,0.0,0.0,0.0,18.0,7.0,6.0,11.0,24.0
Togo (TOG),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Tonga (TGA),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Trinidad and Tobago (TRI) [TRI],16.0,2.0,5.0,11.0,18.0,3.0,0.0,0.0,0.0,0.0,19.0,2.0,5.0,11.0,18.0
Tunisia (TUN),13.0,3.0,3.0,4.0,10.0,0.0,0.0,0.0,0.0,0.0,13.0,3.0,3.0,4.0,10.0
Turkey (TUR),21.0,39.0,25.0,24.0,88.0,16.0,0.0,0.0,0.0,0.0,37.0,39.0,25.0,24.0,88.0
Uganda (UGA),14.0,2.0,3.0,2.0,7.0,0.0,0.0,0.0,0.0,0.0,14.0,2.0,3.0,2.0,7.0
Ukraine (UKR),5.0,33.0,27.0,55.0,115.0,6.0,2.0,1.0,4.0,7.0,11.0,35.0,28.0,59.0,122.0
United Arab Emirates (UAE),8.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,8.0,1.0,0.0,0.0,1.0
United States (USA) [P] [Q] [R] [Z],26.0,976.0,757.0,666.0,2399.0,22.0,96.0,102.0,84.0,282.0,48.0,1072.0,859.0,750.0,2681.0
Uruguay (URU),20.0,2.0,2.0,6.0,10.0,1.0,0.0,0.0,0.0,0.0,21.0,2.0,2.0,6.0,10.0
Uzbekistan (UZB),5.0,5.0,5.0,10.0,20.0,6.0,1.0,0.0,0.0,1.0,11.0,6.0,5.0,10.0,21.0
Venezuela (VEN),17.0,2.0,2.0,8.0,12.0,4.0,0.0,0.0,0.0,0.0,21.0,2.0,2.0,8.0,12.0
Vietnam (VIE),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Virgin Islands (ISV),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Yugoslavia (YUG) [YUG],16.0,26.0,29.0,28.0,83.0,14.0,0.0,3.0,1.0,4.0,30.0,26.0,32.0,29.0,87.0
Independent Olympic Participants (IOP) [IOP],NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Zambia (ZAM) [ZAM],NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Zimbabwe (ZIM) [ZIM],12.0,3.0,4.0,1.0,8.0,1.0,0.0,0.0,0.0,0.0,13.0,3.0,4.0,1.0,8.0
Mixed team (ZZX) [ZZX],3.0,8.0,5.0,4.0,17.0,0.0,0.0,0.0,0.0,0.0,3.0,8.0,5.0,4.0,17.0
Totals,27.0,4809.0,4775.0,5130.0,14714.0,22.0,959.0,958.0,948.0,2865.0,49.0,5768.0,5733.0,6078.0,17579.0

In [22]:
ganadores_oro['Gold'].count()

100

In [23]:
ganadores_oro = ganadores_oro.dropna()
ganadores_oro

,№ Summer,Gold,Silver,Bronze,Total,№ Winter,Gold.1,Silver.1,Bronze.1,Total.1,№ Games,Gold.2,Silver.2,Bronze.2,Combined total
Algeria (ALG),12.0,5.0,2.0,8.0,15.0,3.0,0.0,0.0,0.0,0.0,15.0,5.0,2.0,8.0,15.0
Argentina (ARG),23.0,18.0,24.0,28.0,70.0,18.0,0.0,0.0,0.0,0.0,41.0,18.0,24.0,28.0,70.0
Armenia (ARM),5.0,1.0,2.0,9.0,12.0,6.0,0.0,0.0,0.0,0.0,11.0,1.0,2.0,9.0,12.0
Australasia (ANZ) [ANZ],2.0,3.0,4.0,5.0,12.0,0.0,0.0,0.0,0.0,0.0,2.0,3.0,4.0,5.0,12.0
Australia (AUS) [AUS] [Z],25.0,139.0,152.0,177.0,468.0,18.0,5.0,3.0,4.0,12.0,43.0,144.0,155.0,181.0,480.0
Austria (AUT),26.0,18.0,33.0,35.0,86.0,22.0,59.0,78.0,81.0,218.0,48.0,77.0,111.0,116.0,304.0
Azerbaijan (AZE),5.0,6.0,5.0,15.0,26.0,5.0,0.0,0.0,0.0,0.0,10.0,6.0,5.0,15.0,26.0
Bahamas (BAH),15.0,5.0,2.0,5.0,12.0,0.0,0.0,0.0,0.0,0.0,15.0,5.0,2.0,5.0,12.0
Belarus (BLR),5.0,12.0,24.0,39.0,75.0,6.0,6.0,4.0,5.0,15.0,11.0,18.0,28.0,44.0,90.0
Belgium (BEL),25.0,37.0,52.0,53.0,142.0,20.0,1.0,1.0,3.0,5.0,45.0,38.0,53.0,56.0,147.0
Brazil (BRA),21.0,23.0,30.0,55.0,108.0,7.0,0.0,0.0,0.0,0.0,28.0,23.0,30.0,55.0,108.0
Bulgaria (BUL) [H],19.0,51.0,85.0,78.0,214.0,19.0,1.0,2.0,3.0,6.0,38.0,52.0,87.0,81.0,220.0
Burundi (BDI),5.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,5.0,1.0,0.0,0.0,1.0
Cameroon (CMR),13.0,3.0,1.0,1.0,5.0,1.0,0.0,0.0,0.0,0.0,14.0,3.0,1.0,1.0,5.0
Canada (CAN),25.0,59.0,99.0,121.0,279.0,22.0,62.0,56.0,52.0,170.0,47.0,121.0,155.0,173.0,449.0
Chile (CHI) [I],22.0,2.0,7.0,4.0,13.0,16.0,0.0,0.0,0.0,0.0,38.0,2.0,7.0,4.0,13.0
China (CHN) [CHN],9.0,201.0,146.0,126.0,473.0,10.0,12.0,22.0,19.0,53.0,19.0,213.0,168.0,145.0,526.0
Colombia (COL),18.0,2.0,6.0,11.0,19.0,1.0,0.0,0.0,0.0,0.0,19.0,2.0,6.0,11.0,19.0
Costa Rica (CRC),14.0,1.0,1.0,2.0,4.0,6.0,0.0,0.0,0.0,0.0,20.0,1.0,1.0,2.0,4.0
Croatia (CRO),6.0,6.0,7.0,10.0,23.0,7.0,4.0,6.0,1.0,11.0,13.0,10.0,13.0,11.0,34.0
Cuba (CUB) [Z],19.0,72.0,67.0,70.0,209.0,0.0,0.0,0.0,0.0,0.0,19.0,72.0,67.0,70.0,209.0
Czech Republic (CZE) [CZE],5.0,14.0,15.0,15.0,44.0,6.0,7.0,9.0,8.0,24.0,11.0,21.0,24.0,23.0,68.0
Czechoslovakia (TCH) [TCH],16.0,49.0,49.0,45.0,143.0,16.0,2.0,8.0,15.0,25.0,32.0,51.0,57.0,60.0,168.0
Denmark (DEN) [Z],26.0,43.0,68.0,68.0,179.0,13.0,0.0,1.0,0.0,1.0,39.0,43.0,69.0,68.0,180.0
Dominican Republic (DOM),13.0,3.0,2.0,1.0,6.0,0.0,0.0,0.0,0.0,0.0,13.0,3.0,2.0,1.0,6.0
Ecuador (ECU),13.0,1.0,1.0,0.0,2.0,0.0,0.0,0.0,0.0,0.0,13.0,1.0,1.0,0.0,2.0
Egypt (EGY) [EGY] [Z],21.0,7.0,9.0,10.0,26.0,1.0,0.0,0.0,0.0,0.0,22.0,7.0,9.0,10.0,26.0
Estonia (EST),11.0,9.0,9.0,15.0,33.0,9.0,4.0,2.0,1.0,7.0,20.0,13.0,11.0,16.0,40.0
Ethiopia (ETH),12.0,21.0,7.0,17.0,45.0,2.0,0.0,0.0,0.0,0.0,14.0,21.0,7.0,17.0,45.0
Finland (FIN),24.0,101.0,84.0,117.0,302.0,22.0,42.0,62.0,57.0,161.0,46.0,143.0,146.0,174.0,463.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Russia (RUS) [RUS],5.0,132.0,121.0,142.0,395.0,6.0,49.0,40.0,35.0,124.0,11.0,181.0,161.0,177.0,519.0
Russian Empire (RU1) [RU1],3.0,1.0,4.0,3.0,8.0,0.0,0.0,0.0,0.0,0.0,3.0,1.0,4.0,3.0,8.0
Soviet Union (URS) [URS],9.0,395.0,319.0,296.0,1010.0,9.0,78.0,57.0,59.0,194.0,18.0,473.0,376.0,355.0,1204.0
Unified Team (EUN) [EUN],1.0,45.0,38.0,29.0,112.0,1.0,9.0,6.0,8.0,23.0,2.0,54.0,44.0,37.0,135.0
Serbia (SRB) [SRB],3.0,1.0,2.0,4.0,7.0,2.0,0.0,0.0,0.0,0.0,5.0,1.0,2.0,4.0,7.0
Serbia and Montenegro (SCG) [SCG],3.0,2.0,4.0,3.0,9.0,3.0,0.0,0.0,0.0,0.0,6.0,2.0,4.0,3.0,9.0
Slovakia (SVK) [SVK],5.0,7.0,9.0,8.0,24.0,6.0,2.0,2.0,1.0,5.0,11.0,9.0,11.0,9.0,29.0
Slovenia (SLO),6.0,4.0,6.0,9.0,19.0,7.0,2.0,4.0,9.0,15.0,13.0,6.0,10.0,18.0,34.0
South Africa (RSA),18.0,23.0,26.0,27.0,76.0,6.0,0.0,0.0,0.0,0.0,24.0,23.0,26.0,27.0,76.0
Spain (ESP) [Z],22.0,37.0,59.0,35.0,131.0,19.0,1.0,0.0,1.0,2.0,41.0,38.0,59.0,36.0,133.0
Suriname (SUR) [E],11.0,1.0,0.0,1.0,2.0,0.0,0.0,0.0,0.0,0.0,11.0,1.0,0.0,1.0,2.0
Sweden (SWE) [Z],26.0,143.0,164.0,176.0,483.0,22.0,50.0,40.0,54.0,144.0,48.0,193.0,204.0,230.0,627.0
Switzerland (SUI),27.0,47.0,73.0,65.0,185.0,22.0,50.0,40.0,48.0,138.0,49.0,97.0,113.0,113.0,323.0
Syria (SYR),12.0,1.0,1.0,1.0,3.0,0.0,0.0,0.0,0.0,0.0,12.0,1.0,1.0,1.0,3.0
Chinese Taipei (TPE) [TPE] [TPE2],13.0,2.0,7.0,12.0,21.0,11.0,0.0,0.0,0.0,0.0,24.0,2.0,7.0,12.0,21.0
Thailand (THA),15.0,7.0,6.0,11.0,24.0,3.0,0.0,0.0,0.0,0.0,18.0,7.0,6.0,11.0,24.0
Trinidad and Tobago (TRI) [TRI],16.0,2.0,5.0,11.0,18.0,3.0,0.0,0.0,0.0,0.0,19.0,2.0,5.0,11.0,18.0
Tunisia (TUN),13.0,3.0,3.0,4.0,10.0,0.0,0.0,0.0,0.0,0.0,13.0,3.0,3.0,4.0,10.0
Turkey (TUR),21.0,39.0,25.0,24.0,88.0,16.0,0.0,0.0,0.0,0.0,37.0,39.0,25.0,24.0,88.0
Uganda (UGA),14.0,2.0,3.0,2.0,7.0,0.0,0.0,0.0,0.0,0.0,14.0,2.0,3.0,2.0,7.0
Ukraine (UKR),5.0,33.0,27.0,55.0,115.0,6.0,2.0,1.0,4.0,7.0,11.0,35.0,28.0,59.0,122.0
United Arab Emirates (UAE),8.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,8.0,1.0,0.0,0.0,1.0
United States (USA) [P] [Q] [R] [Z],26.0,976.0,757.0,666.0,2399.0,22.0,96.0,102.0,84.0,282.0,48.0,1072.0,859.0,750.0,2681.0
Uruguay (URU),20.0,2.0,2.0,6.0,10.0,1.0,0.0,0.0,0.0,0.0,21.0,2.0,2.0,6.0,10.0
Uzbekistan (UZB),5.0,5.0,5.0,10.0,20.0,6.0,1.0,0.0,0.0,1.0,11.0,6.0,5.0,10.0,21.0
Venezuela (VEN),17.0,2.0,2.0,8.0,12.0,4.0,0.0,0.0,0.0,0.0,21.0,2.0,2.0,8.0,12.0
Yugoslavia (YUG) [YUG],16.0,26.0,29.0,28.0,83.0,14.0,0.0,3.0,1.0,4.0,30.0,26.0,32.0,29.0,87.0
Zimbabwe (ZIM) [ZIM],12.0,3.0,4.0,1.0,8.0,1.0,0.0,0.0,0.0,0.0,13.0,3.0,4.0,1.0,8.0
Mixed team (ZZX) [ZZX],3.0,8.0,5.0,4.0,17.0,0.0,0.0,0.0,0.0,0.0,3.0,8.0,5.0,4.0,17.0
Totals,27.0,4809.0,4775.0,5130.0,14714.0,22.0,959.0,958.0,948.0,2865.0,49.0,5768.0,5733.0,6078.0,17579.0

In [24]:
ganadores_oro2 = df[df['Gold'] > 0]
ganadores_oro2

,№ Summer,Gold,Silver,Bronze,Total,№ Winter,Gold.1,Silver.1,Bronze.1,Total.1,№ Games,Gold.2,Silver.2,Bronze.2,Combined total
Algeria (ALG),12,5,2,8,15,3,0,0,0,0,15,5,2,8,15
Argentina (ARG),23,18,24,28,70,18,0,0,0,0,41,18,24,28,70
Armenia (ARM),5,1,2,9,12,6,0,0,0,0,11,1,2,9,12
Australasia (ANZ) [ANZ],2,3,4,5,12,0,0,0,0,0,2,3,4,5,12
Australia (AUS) [AUS] [Z],25,139,152,177,468,18,5,3,4,12,43,144,155,181,480
Austria (AUT),26,18,33,35,86,22,59,78,81,218,48,77,111,116,304
Azerbaijan (AZE),5,6,5,15,26,5,0,0,0,0,10,6,5,15,26
Bahamas (BAH),15,5,2,5,12,0,0,0,0,0,15,5,2,5,12
Belarus (BLR),5,12,24,39,75,6,6,4,5,15,11,18,28,44,90
Belgium (BEL),25,37,52,53,142,20,1,1,3,5,45,38,53,56,147
Brazil (BRA),21,23,30,55,108,7,0,0,0,0,28,23,30,55,108
Bulgaria (BUL) [H],19,51,85,78,214,19,1,2,3,6,38,52,87,81,220
Burundi (BDI),5,1,0,0,1,0,0,0,0,0,5,1,0,0,1
Cameroon (CMR),13,3,1,1,5,1,0,0,0,0,14,3,1,1,5
Canada (CAN),25,59,99,121,279,22,62,56,52,170,47,121,155,173,449
Chile (CHI) [I],22,2,7,4,13,16,0,0,0,0,38,2,7,4,13
China (CHN) [CHN],9,201,146,126,473,10,12,22,19,53,19,213,168,145,526
Colombia (COL),18,2,6,11,19,1,0,0,0,0,19,2,6,11,19
Costa Rica (CRC),14,1,1,2,4,6,0,0,0,0,20,1,1,2,4
Croatia (CRO),6,6,7,10,23,7,4,6,1,11,13,10,13,11,34
Cuba (CUB) [Z],19,72,67,70,209,0,0,0,0,0,19,72,67,70,209
Czech Republic (CZE) [CZE],5,14,15,15,44,6,7,9,8,24,11,21,24,23,68
Czechoslovakia (TCH) [TCH],16,49,49,45,143,16,2,8,15,25,32,51,57,60,168
Denmark (DEN) [Z],26,43,68,68,179,13,0,1,0,1,39,43,69,68,180
Dominican Republic (DOM),13,3,2,1,6,0,0,0,0,0,13,3,2,1,6
Ecuador (ECU),13,1,1,0,2,0,0,0,0,0,13,1,1,0,2
Egypt (EGY) [EGY] [Z],21,7,9,10,26,1,0,0,0,0,22,7,9,10,26
Estonia (EST),11,9,9,15,33,9,4,2,1,7,20,13,11,16,40
Ethiopia (ETH),12,21,7,17,45,2,0,0,0,0,14,21,7,17,45
Finland (FIN),24,101,84,117,302,22,42,62,57,161,46,143,146,174,463
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Russia (RUS) [RUS],5,132,121,142,395,6,49,40,35,124,11,181,161,177,519
Russian Empire (RU1) [RU1],3,1,4,3,8,0,0,0,0,0,3,1,4,3,8
Soviet Union (URS) [URS],9,395,319,296,1010,9,78,57,59,194,18,473,376,355,1204
Unified Team (EUN) [EUN],1,45,38,29,112,1,9,6,8,23,2,54,44,37,135
Serbia (SRB) [SRB],3,1,2,4,7,2,0,0,0,0,5,1,2,4,7
Serbia and Montenegro (SCG) [SCG],3,2,4,3,9,3,0,0,0,0,6,2,4,3,9
Slovakia (SVK) [SVK],5,7,9,8,24,6,2,2,1,5,11,9,11,9,29
Slovenia (SLO),6,4,6,9,19,7,2,4,9,15,13,6,10,18,34
South Africa (RSA),18,23,26,27,76,6,0,0,0,0,24,23,26,27,76
Spain (ESP) [Z],22,37,59,35,131,19,1,0,1,2,41,38,59,36,133
Suriname (SUR) [E],11,1,0,1,2,0,0,0,0,0,11,1,0,1,2
Sweden (SWE) [Z],26,143,164,176,483,22,50,40,54,144,48,193,204,230,627
Switzerland (SUI),27,47,73,65,185,22,50,40,48,138,49,97,113,113,323
Syria (SYR),12,1,1,1,3,0,0,0,0,0,12,1,1,1,3
Chinese Taipei (TPE) [TPE] [TPE2],13,2,7,12,21,11,0,0,0,0,24,2,7,12,21
Thailand (THA),15,7,6,11,24,3,0,0,0,0,18,7,6,11,24
Trinidad and Tobago (TRI) [TRI],16,2,5,11,18,3,0,0,0,0,19,2,5,11,18
Tunisia (TUN),13,3,3,4,10,0,0,0,0,0,13,3,3,4,10
Turkey (TUR),21,39,25,24,88,16,0,0,0,0,37,39,25,24,88
Uganda (UGA),14,2,3,2,7,0,0,0,0,0,14,2,3,2,7
Ukraine (UKR),5,33,27,55,115,6,2,1,4,7,11,35,28,59,122
United Arab Emirates (UAE),8,1,0,0,1,0,0,0,0,0,8,1,0,0,1
United States (USA) [P] [Q] [R] [Z],26,976,757,666,2399,22,96,102,84,282,48,1072,859,750,2681
Uruguay (URU),20,2,2,6,10,1,0,0,0,0,21,2,2,6,10
Uzbekistan (UZB),5,5,5,10,20,6,1,0,0,1,11,6,5,10,21
Venezuela (VEN),17,2,2,8,12,4,0,0,0,0,21,2,2,8,12
Yugoslavia (YUG) [YUG],16,26,29,28,83,14,0,3,1,4,30,26,32,29,87
Zimbabwe (ZIM) [ZIM],12,3,4,1,8,1,0,0,0,0,13,3,4,1,8
Mixed team (ZZX) [ZZX],3,8,5,4,17,0,0,0,0,0,3,8,5,4,17
Totals,27,4809,4775,5130,14714,22,959,958,948,2865,49,5768,5733,6078,17579

In [25]:
ganadores_oro3 = df[(df['Gold'] > 0) & (df['Gold.1'] > 0)]
ganadores_oro3

,№ Summer,Gold,Silver,Bronze,Total,№ Winter,Gold.1,Silver.1,Bronze.1,Total.1,№ Games,Gold.2,Silver.2,Bronze.2,Combined total
Australia (AUS) [AUS] [Z],25,139,152,177,468,18,5,3,4,12,43,144,155,181,480
Austria (AUT),26,18,33,35,86,22,59,78,81,218,48,77,111,116,304
Belarus (BLR),5,12,24,39,75,6,6,4,5,15,11,18,28,44,90
Belgium (BEL),25,37,52,53,142,20,1,1,3,5,45,38,53,56,147
Bulgaria (BUL) [H],19,51,85,78,214,19,1,2,3,6,38,52,87,81,220
Canada (CAN),25,59,99,121,279,22,62,56,52,170,47,121,155,173,449
China (CHN) [CHN],9,201,146,126,473,10,12,22,19,53,19,213,168,145,526
Croatia (CRO),6,6,7,10,23,7,4,6,1,11,13,10,13,11,34
Czech Republic (CZE) [CZE],5,14,15,15,44,6,7,9,8,24,11,21,24,23,68
Czechoslovakia (TCH) [TCH],16,49,49,45,143,16,2,8,15,25,32,51,57,60,168
Estonia (EST),11,9,9,15,33,9,4,2,1,7,20,13,11,16,40
Finland (FIN),24,101,84,117,302,22,42,62,57,161,46,143,146,174,463
France (FRA) [O] [P] [Z],27,202,223,246,671,22,31,31,47,109,49,233,254,293,780
Germany (GER) [GER] [Z],15,174,182,217,573,11,78,78,53,209,26,252,260,270,782
United Team of Germany (EUA) [EUA],3,28,54,36,118,3,8,6,5,19,6,36,60,41,137
East Germany (GDR) [GDR],5,153,129,127,409,6,39,36,35,110,11,192,165,162,519
West Germany (FRG) [FRG],5,56,67,81,204,6,11,15,13,39,11,67,82,94,243
Great Britain (GBR) [GBR] [Z],27,236,272,272,780,22,10,4,12,26,49,246,276,284,806
Italy (ITA) [M] [S],26,198,166,185,549,22,37,34,43,114,48,235,200,228,663
Japan (JPN),21,130,126,142,398,20,10,17,18,45,41,140,143,160,443
Kazakhstan (KAZ),5,16,17,19,52,6,1,3,3,7,11,17,20,22,59
South Korea (KOR),16,81,82,80,243,17,26,17,10,53,33,107,99,90,296
Netherlands (NED) [Z],25,77,85,104,266,20,37,38,35,110,45,114,123,139,376
Norway (NOR) [Q],24,56,49,43,148,22,118,111,100,329,46,174,160,143,477
Poland (POL),20,64,82,125,271,22,6,7,7,20,42,70,89,132,291
Russia (RUS) [RUS],5,132,121,142,395,6,49,40,35,124,11,181,161,177,519
Soviet Union (URS) [URS],9,395,319,296,1010,9,78,57,59,194,18,473,376,355,1204
Unified Team (EUN) [EUN],1,45,38,29,112,1,9,6,8,23,2,54,44,37,135
Slovakia (SVK) [SVK],5,7,9,8,24,6,2,2,1,5,11,9,11,9,29
Slovenia (SLO),6,4,6,9,19,7,2,4,9,15,13,6,10,18,34
Spain (ESP) [Z],22,37,59,35,131,19,1,0,1,2,41,38,59,36,133
Sweden (SWE) [Z],26,143,164,176,483,22,50,40,54,144,48,193,204,230,627
Switzerland (SUI),27,47,73,65,185,22,50,40,48,138,49,97,113,113,323
Ukraine (UKR),5,33,27,55,115,6,2,1,4,7,11,35,28,59,122
United States (USA) [P] [Q] [R] [Z],26,976,757,666,2399,22,96,102,84,282,48,1072,859,750,2681
Uzbekistan (UZB),5,5,5,10,20,6,1,0,0,1,11,6,5,10,21
Totals,27,4809,4775,5130,14714,22,959,958,948,2865,49,5768,5733,6078,17579

## Group by <a id=id7> <a/>